// Auto-generated by scripts/generate-images.js
// Do not edit manually. Run `npm run generate-images` to regenerate.

export interface MediaItem {
  src: string;
  label?: string;
  title?: string;
}

export const exteriorImages: MediaItem[] = [
  {
    "src": "/images/exterior/photo_1_2026-05-23_01-23-57.jpg",
    "label": "exterior 1"
  },
  {
    "src": "/images/exterior/photo_2_2026-05-23_01-23-57.jpg",
    "label": "exterior 2"
  },
  {
    "src": "/images/exterior/photo_3_2026-05-23_01-23-57.jpg",
    "label": "exterior 3"
  },
  {
    "src": "/images/exterior/photo_4_2026-05-23_01-23-57.jpg",
    "label": "exterior 4"
  },
  {
    "src": "/images/exterior/photo_5_2026-05-23_01-23-57.jpg",
    "label": "exterior 5"
  }
];

export const cabinsImages: MediaItem[] = [
  {
    "src": "/images/cabins/photo_10_2026-05-23_01-21-10.jpg",
    "label": "cabins 1"
  },
  {
    "src": "/images/cabins/photo_11_2026-05-23_01-21-10.jpg",
    "label": "cabins 2"
  },
  {
    "src": "/images/cabins/photo_12_2026-05-23_01-21-10.jpg",
    "label": "cabins 3"
  },
  {
    "src": "/images/cabins/photo_13_2026-05-23_01-21-10.jpg",
    "label": "cabins 4"
  },
  {
    "src": "/images/cabins/photo_14_2026-05-23_01-21-10.jpg",
    "label": "cabins 5"
  },
  {
    "src": "/images/cabins/photo_15_2026-05-23_01-21-11.jpg",
    "label": "cabins 6"
  },
  {
    "src": "/images/cabins/photo_16_2026-05-23_01-21-11.jpg",
    "label": "cabins 7"
  },
  {
    "src": "/images/cabins/photo_17_2026-05-23_01-21-11.jpg",
    "label": "cabins 8"
  },
  {
    "src": "/images/cabins/photo_18_2026-05-23_01-21-11.jpg",
    "label": "cabins 9"
  },
  {
    "src": "/images/cabins/photo_19_2026-05-23_01-21-11.jpg",
    "label": "cabins 10"
  },
  {
    "src": "/images/cabins/photo_1_2026-05-23_01-21-10.jpg",
    "label": "cabins 11"
  },
  {
    "src": "/images/cabins/photo_20_2026-05-23_01-21-11.jpg",
    "label": "cabins 12"
  },
  {
    "src": "/images/cabins/photo_21_2026-05-23_01-21-11.jpg",
    "label": "cabins 13"
  },
  {
    "src": "/images/cabins/photo_22_2026-05-23_01-21-11.jpg",
    "label": "cabins 14"
  },
  {
    "src": "/images/cabins/photo_23_2026-05-23_01-21-11.jpg",
    "label": "cabins 15"
  },
  {
    "src": "/images/cabins/photo_2_2026-05-23_01-21-10.jpg",
    "label": "cabins 16"
  },
  {
    "src": "/images/cabins/photo_3_2026-05-23_01-21-10.jpg",
    "label": "cabins 17"
  },
  {
    "src": "/images/cabins/photo_4_2026-05-23_01-21-10.jpg",
    "label": "cabins 18"
  },
  {
    "src": "/images/cabins/photo_5_2026-05-23_01-21-10.jpg",
    "label": "cabins 19"
  },
  {
    "src": "/images/cabins/photo_6_2026-05-23_01-21-10.jpg",
    "label": "cabins 20"
  },
  {
    "src": "/images/cabins/photo_7_2026-05-23_01-21-10.jpg",
    "label": "cabins 21"
  },
  {
    "src": "/images/cabins/photo_8_2026-05-23_01-21-10.jpg",
    "label": "cabins 22"
  },
  {
    "src": "/images/cabins/photo_9_2026-05-23_01-21-10.jpg",
    "label": "cabins 23"
  }
];

export const foodImages: MediaItem[] = [
  {
    "src": "/images/food/IMG-20260522-WA0156.jpg",
    "label": "food 1"
  },
  {
    "src": "/images/food/WhatsApp Image 2025-08-10 at 22.52.57_b6dc9eaa.jpg",
    "label": "food 2"
  },
  {
    "src": "/images/food/WhatsApp Image 2025-08-10 at 22.52.57_d08c6086.jpg",
    "label": "food 3"
  }
];

export const foodVideos: MediaItem[] = [
  {
    "src": "/images/food/VID-20260522-WA0159.mp4",
    "title": "food Video 1"
  }
];

export const videosList: MediaItem[] = [
  {
    "src": "/images/videos/VID-20260522-WA0160.mp4",
    "title": "videos Video 1"
  },
  {
    "src": "/images/videos/VID-20260522-WA0161.mp4",
    "title": "videos Video 2"
  },
  {
    "src": "/images/videos/VID-20260522-WA0162.mp4",
    "title": "videos Video 3"
  },
  {
    "src": "/images/videos/VID-20260523-WA0001.mp4",
    "title": "videos Video 4"
  },
  {
    "src": "/images/videos/VID-20260523-WA0002.mp4",
    "title": "videos Video 5"
  }
];
