const fs = require("fs");
const path = require("path");

const imagesDir = path.join(__dirname, "..", "public", "images");
const outDir = path.join(__dirname, "..", "config");

const imageExts = new Set([".jpg", ".jpeg", ".png", ".webp", ".avif", ".gif"]);
const videoExts = new Set([".mp4", ".webm", ".mov", ".avi"]);

const BASE_PATH = "/octopus-frontend-";

function labelFromName(name, index) {
  const clean = name.replace(/\.[^.]+$/, "").replace(/[-_]/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
  if (/^(Photo|IMG|VID|WhatsApp|Screenshot)/i.test(clean)) {
    return null;
  }
  return clean;
}

function scanDir(dir) {
  const results = { images: [], videos: [] };
  if (!fs.existsSync(dir)) return results;
  const files = fs.readdirSync(dir).sort();
  for (const file of files) {
    const ext = path.extname(file).toLowerCase();
    const fullPath = path.join(dir, file);
    const stat = fs.statSync(fullPath);
    if (!stat.isFile()) continue;
    const relPath = BASE_PATH + "/images/" + path.basename(dir) + "/" + file;
    if (imageExts.has(ext)) {
      const label = labelFromName(file, results.images.length + 1) || `${path.basename(dir)} ${results.images.length + 1}`;
      results.images.push({ src: relPath, label });
    } else if (videoExts.has(ext)) {
      const title = labelFromName(file, results.videos.length + 1) || `${path.basename(dir)} Video ${results.videos.length + 1}`;
      results.videos.push({ src: relPath, title });
    }
  }
  return results;
}

const exterior = scanDir(path.join(imagesDir, "exterior"));
const cabins = scanDir(path.join(imagesDir, "cabins"));
const food = scanDir(path.join(imagesDir, "food"));
const videos = scanDir(path.join(imagesDir, "videos"));

const data = `// Auto-generated by scripts/generate-images.js
// Do not edit manually. Run \`npm run generate-images\` to regenerate.

export interface MediaItem {
  src: string;
  label?: string;
  title?: string;
}

export const exteriorImages: MediaItem[] = ${JSON.stringify(exterior.images, null, 2)};

export const cabinsImages: MediaItem[] = ${JSON.stringify(cabins.images, null, 2)};

export const foodImages: MediaItem[] = ${JSON.stringify(food.images, null, 2)};

export const foodVideos: MediaItem[] = ${JSON.stringify(food.videos, null, 2)};

export const videosList: MediaItem[] = ${JSON.stringify(videos.videos, null, 2)};
`;

if (!fs.existsSync(outDir)) {
  fs.mkdirSync(outDir, { recursive: true });
}

fs.writeFileSync(path.join(outDir, "images.ts"), data, "utf-8");
console.log("Generated config/images.ts");
console.log(`  exterior: ${exterior.images.length} images`);
console.log(`  cabins: ${cabins.images.length} images`);
console.log(`  food: ${food.images.length} images, ${food.videos.length} videos`);
console.log(`  videos: ${videos.videos.length} videos`);
